version: '3.8'

services:
  jenkins:
    build:
      context: ./jenkins
      dockerfile: Dockerfile
    container_name: jenkins
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./jenkins/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./shared:/shared 
      - ../ansible:/ansible
    networks:
      - devsecops-net

  mysql:
    image: mysql:9.1
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: petclinic
      MYSQL_USER: petclinic
      MYSQL_PASSWORD: petclinic
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - devsecops-net

  postgres:
    image: postgres:17.0
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: petclinic
      POSTGRES_USER: petclinic
      POSTGRES_PASSWORD: petclinic
    ports:
      - "5432:5432"
    networks:
      - devsecops-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U petclinic"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - "9090:9090"
    networks:
      - devsecops-net
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    ports:
      - "3000:3000"
    networks:
      - devsecops-net
    restart: always
    depends_on:
      - prometheus
  
  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    ports:
      - "9000:9000"
    networks:
      - devsecops-net
    environment:
    - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    - sonar.search.javaAdditionalOpts=-Des.disk.watermark.low=1gb -Des.disk.watermark.high=1gb -Des.disk.watermark.flood_stage=512mb
    volumes:
      - ./sonar/data:/opt/sonarqube/data
      - ./sonar/extensions:/opt/sonarqube/extensions
    restart: always

  owasp-zap:
    image: ghcr.io/zaproxy/zaproxy:latest
    container_name: owasp-zap
    entrypoint: [ "tail", "-f", "/dev/null" ]
    networks:
      - devsecops-net
    volumes:
      - ./zap:/zap/wrk 
    working_dir: /zap/wrk

networks:
  devsecops-net:
    external: true
